version: '3.8'

services:
  portfolio-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_RAPID_API_KEY: ${REACT_APP_RAPID_API_KEY}
        REACT_APP_PORTFOLIO_API_KEY: ${REACT_APP_PORTFOLIO_API_KEY}
    container_name: personal_portfolio_v3
    ports:
      - "8012:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
